/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/whale.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/whale.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="Whale" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Whale_1" geometry={nodes.Whale_1.geometry} material={materials.Top} skeleton={nodes.Whale_1.skeleton} />
            <skinnedMesh name="Whale_2" geometry={nodes.Whale_2.geometry} material={materials.Bottom} skeleton={nodes.Whale_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/whale.glb')
